---
# tasks file for osp-user

  - name: get the osp auth
    os_auth:
    region_name: "{{ region }}"
    cert: "{{ user_cert }}"
    key: "{{ user_key }}"
    cacert: "{{ user_cacert }}"
    endpoint_type: "{{ user_enpoint }}"

  - name: get user information
    os_user_facts:
      name: "{{ user }}"
      cert: "{{ user_cert }}"
      key: "{{ user_key }}"
      cacert: "{{ user_cacert }}"
      region_name: "{{ region }}"
      domain: " {{ domain_name }}" 
      availability_zone: "{{ zone }}"
      enpoint_type: "{{ user_endpoint }}"
    debug:
      var: openstack_users

  - name: create the user
    os_user:
      endpoint_type: "{{  }}"
      auth: "{{ user_auth }}"
      cert: "{{ user_cert }}"
      key: "{{ user_key }}"
      cacert: "{{ user_cacert }}"
      default_project: "{{ user_project }}"
      name: "{{ user_name }}"
      description: "{{ user_descript }}"
      email: "{{ user_email }}"
      enabled: "{{ user_status }}"
      password: "{{ user_passwd }}"
      update_password: "{{ user_passwd_create }}"
    with_subelements:
      - 
    when: 




