---
# tasks file for osp-user

  - name: get the osp auth
    os_auth:
    region_name: "{{ region }}"
    cert: "{{ user_cert }}"
    key: "{{ user_key }}"
    cacert: "{{ user_cacert }}"
    endpoint_type: "{{ osp_user.api.endpoint_type }}"

  - name: get user information
    os_user_facts:
      name: "{{ user }}"
      cert: "{{ user_cert }}"
      key: "{{ user_key }}"
      cacert: "{{ user_cacert }}"
      region_name: "{{ osp_user.api.region_name }}"
      domain: " {{ osp_user.api.user_domain_name }}" 
      enpoint_type: "{{ osp_user.api.endpoint_type }}"
    

  - name: create the user
    os_user:
      endpoint_type: "{{ osp_user.api.endpoint_type  }}"
      auth: "{{ osp_user.api.auth }}"
      default_project: "{{ osp_user.default_project }}"
      name: "{{ item.1.admin.name }}"
      description: "{{ item.1.admin.description  }}"
      email: "{{ item.1.admin.email }}"
      enabled: "{{ item.1.admin.enabled }}"
      password: "{{ item.1.admin.password }}"
      update_password: "{{ item.1.admin.update_password }}"
    with_subelements:
      - "{{ osp_user.admin }}"
      - "{{ osp_user.users }}"
 




