---
# tasks file for osp-user

  - name: get the osp auth
    os_auth:
    region_name: "{{ region }}"
    cert: "{{ user_cert }}"
    key: "{{ user_key }}"
    cacert: "{{ user_cacert }}"
    endpoint_type: "{{ user_enpoint }}"

  - name: get user information
    os_user_facts:
      name: "{{ user }}"
      cert: "{{ user_cert }}"
      key: "{{ user_key }}"
      cacert: "{{ user_cacert }}"
      region_name: "{{ region }}"
      domain: " {{ domain_name }}" 
      availability_zone: "{{ zone }}"
      enpoint_type: "{{ user_endpoint }}"
    debug:
      var: openstack_users

  - name: create the user
    os_user:
      endpoint_type: "{{ osp_user.user.endpoint_type  }}"
      default_project: "{{ user_project }}"
      name: "{{ osp_user.users.username }}"
      description: "{{ osp_user.user.user_description }}"
      email: "{{ osp_user.user.user_email }}"
      enabled: "{{ osp_user.user.user_status }}"
      password: "{{ osp_user.user.user_passwd }}"
      update_password: "{{ osp_user.user.user_passwd_create }}"
    with_subelements:
      - "{{ osp_user.admin }}"
      - "{{ osp_user.users }}"
    when: 




